import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import { truncateAddress } from "../services/address.service";
import { ConnectedSite } from "../components/ConnectedSite";

const connectZecrey = async (): Promise<string | undefined> => {
  let zecrey = (window as any).zecrey;
  console.log(zecrey);
  if (zecrey) {
    const result: string[] = await zecrey.request({
      method: "eth_requestAccounts",
    });
    return result[0];
  } else {
    window.open(
      "https://chrome.google.com/webstore/detail/zecrey/ojbpcbinjmochkhelkflddfnmcceomdi"
    );
  }
};

const Home: NextPage = () => {
  const [isConnected, setIsConnected] = useState(false);
  const [address, setAddress] = useState<string>();

  const handleConnectClick = async () => {
    const address = await connectZecrey();
    setIsConnected(true);
    setAddress(address);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Zecrey test Dapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/zecrey.png" />
      </Head>

      <main className={styles.main}>
        {isConnected ? (
          <>
            <h3 style={{ margin: 0 }}>
              Wallet address: <code>{address && truncateAddress(address)}</code>
            </h3>
            <ConnectedSite />
          </>
        ) : (
          <>
            <button className={styles.connect} onClick={handleConnectClick}>
              Connect Wallet
            </button>
            <p>First connect wallet to use dapp.</p>
          </>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/zecrey.png" alt="zecrey Logo" width={16} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
