import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import { truncateAddress } from "../services/address.service";
import { ConnectedSite } from "../components/ConnectedSite";
import { useRouter } from "next/router";

const connectZecrey = async (
  type: "evm" | "near" | "l2"
): Promise<string | undefined> => {
  const zecrey = (window as any).zecrey;
  let method;
  switch (type) {
    case "evm":
      method = "eth_requestAccounts";
      break;
    case "near":
      method = "near_requestAccounts";
      break;
    case "l2":
      method = "zecrey_requestAccounts";
      break;
    default:
      break;
  }
  if (!method) return;
  if (zecrey) {
    const result: string[] = await zecrey.request({
      method,
    });
    return result[0];
  } else {
    window.open(
      "https://chrome.google.com/webstore/detail/zecrey/ojbpcbinjmochkhelkflddfnmcceomdi"
    );
  }
};

const Home: NextPage = () => {
  const [isConnected, setIsConnected] = useState(false);
  const [address, setAddress] = useState<string>();
  const router = useRouter();

  const handleConnectClick = async () => {
    const address = await connectZecrey("evm");
    setIsConnected(true);
    setAddress(address);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Zecrey test Dapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/zecrey.png" />
      </Head>

      <main className={styles.main}>
        {isConnected && address ? (
          <>
            <h3 style={{ margin: 0 }}>
              Wallet address: <code>{address && truncateAddress(address)}</code>
            </h3>
            <ConnectedSite address={address} />
          </>
        ) : (
          <>
            <button className={styles.connect} onClick={handleConnectClick}>
              Connect Wallet - EVM
            </button>
            <button
              className={styles.connect}
              onClick={async () => {
                let accountId = await connectZecrey("near");
                if (accountId) router.push(`/near/${accountId}`);
              }}
            >
              Connect Wallet - Near
            </button>
            <button
              className={styles.connect}
              onClick={async () => {
                let accountName = await connectZecrey("l2");
                if (accountName) router.push(`/l2/${accountName}`);
              }}
            >
              Connect Wallet - L2
            </button>
            <p>First connect wallet to use dapp.</p>
          </>
        )}
      </main>

      <footer className={styles.footer}>
        <a href="https://zecrey.com" target="_blank" rel="noopener noreferrer">
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/zecrey.png" alt="zecrey Logo" width={16} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
